// Generated by bilt-cloud from this project's database schema. Do not edit.
// Regenerated on every schema change; edits are overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

declare module '@biltme/backend' {
  interface Database {
    public: {
      Tables: {
        osm_cache: {
          Row: {
            cache_key: string;
            payload: Json;
            fetched_at: string;
          };
          Insert: {
            cache_key: string;
            payload: Json;
            fetched_at?: string;
          };
          Update: {
            cache_key?: string;
            payload?: Json;
            fetched_at?: string;
          };
          Relationships: [];
        };
      };
      Views: { [_ in never]: never };
      Functions: { [_ in never]: never };
      Enums: { [_ in never]: never };
      CompositeTypes: { [_ in never]: never };
    };
  }
}
